<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFXoQ5Sh\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFXoQ5Sh/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFXoQ5Sh.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFXoQ5Sh\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFXoQ5Sh\appAppKernelProdContainer([
    'container.build_hash' => 'FXoQ5Sh',
    'container.build_id' => '413fb72e',
    'container.build_time' => 1726226545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFXoQ5Sh');
