<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1Xx2GP\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1Xx2GP/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB1Xx2GP.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB1Xx2GP\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerB1Xx2GP\appAppKernelDevDebugContainer([
    'container.build_hash' => 'B1Xx2GP',
    'container.build_id' => 'bed5915a',
    'container.build_time' => 1726832956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1Xx2GP');
